apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: on-call-webapp-rocket
  namespace: monitoring
spec:
  summary: "cluster addons"
  eventMetadata:
    env: "staging"
    cluster: "my-cluster"
    region: "us-east-2"
