apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - podinfo-values.yaml
  - alerts-pager-alert-values.yaml
  - alerts-rocket-alert-values.yaml
